"""
Shared content model for compliance reports.

The PDF, DOCX and XLSX renderers all read from this so the three formats can never
drift apart in wording, penalty figures or legal citations - an enforcement notice
that contradicts its own spreadsheet is worse than no notice at all.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "ADVISORY": 4}

STATUS_LABELS = {
    "COMPLIANT": "COMPLIANT",
    "NON_COMPLIANT": "NON-COMPLIANT",
    "PARTIALLY_COMPLIANT": "PARTIALLY COMPLIANT",
}

DISCLAIMER = (
    "This report is generated by an automated compliance-assistance system. Findings are "
    "derived from optical character recognition of the submitted package images and are "
    "intended to support, not replace, inspection by an authorised officer under the Legal "
    "Metrology Act, 2009. Declarations marked ADVISORY are estimates and require physical "
    "verification before any enforcement action is initiated."
)


def _fmt_datetime(iso: str) -> str:
    if not iso:
        return "-"
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%d %B %Y, %H:%M UTC")
    except ValueError:
        return iso


def _penalty_for(rule_id: str) -> str:
    """Looks the statutory penalty band up from the master rules CSV."""
    try:
        from app.db.db_manager import db_manager

        base = (rule_id or "").split("_MISSING")[0].split("_TAX")[0]
        for rule in db_manager.master_rules:
            rid = str(rule.get("rule_id", ""))
            if rid and (rid == rule_id or rule_id.startswith(rid) or rid.startswith(base)):
                lo = rule.get("penalty_min_inr")
                hi = rule.get("penalty_max_inr")
                if lo and hi:
                    return "Rs. {:,} - Rs. {:,}".format(int(lo), int(hi))
    except Exception:
        pass
    return "As prescribed under the Act"


def build_report_content(inspection: Dict[str, Any]) -> Dict[str, Any]:
    """Flattens a stored inspection into everything a renderer needs."""
    report: Dict[str, Any] = inspection.get("report") or inspection
    meta: Dict[str, Any] = report.get("extracted_metadata") or {}

    violations: List[Dict[str, Any]] = sorted(
        report.get("violations") or [],
        key=lambda v: SEVERITY_ORDER.get(str(v.get("severity", "MEDIUM")).upper(), 9),
    )
    for v in violations:
        v["penalty_band"] = _penalty_for(v.get("rule_id", ""))

    status = inspection.get("status") or report.get("status") or "UNKNOWN"

    declarations = [
        ("Name & address of manufacturer / packer / importer", meta.get("manufacturer_name"), "Rule 6(1)(a)"),
        ("Common or generic name of commodity", inspection.get("product_name") or meta.get("brand_name"), "Rule 6(1)(b)"),
        ("Net quantity", _join(meta.get("net_quantity"), meta.get("unit_of_measure")), "Rule 11 & 12"),
        ("Month & year of manufacture / packing", meta.get("manufacturing_date"), "Rule 6(1)(c)"),
        ("Maximum Retail Price (inclusive of all taxes)", _mrp(meta), "Rule 6(1)(da)"),
        ("Consumer care details", _join(meta.get("consumer_care_email"), meta.get("consumer_care_phone"), sep=" / "), "Rule 6(1)(g)"),
        ("Batch / lot number", meta.get("batch_number"), "Rule 6(1)(f)"),
        ("Country of origin", meta.get("country_of_origin"), "Rule 6(10)"),
    ]

    return {
        "inspection_id": inspection.get("id", "-"),
        "generated_at": datetime.now().strftime("%d %B %Y, %H:%M"),
        "created_at": _fmt_datetime(inspection.get("created_at", "")),
        "officer_name": inspection.get("officer_name") or "-",
        "jurisdiction": inspection.get("jurisdiction") or "-",
        "source": inspection.get("source", "image"),
        "product_name": inspection.get("product_name") or meta.get("brand_name") or "Unidentified product",
        "brand": inspection.get("brand") or meta.get("brand_name") or "-",
        "status": status,
        "status_label": STATUS_LABELS.get(status, status),
        "overall_score": report.get("overall_score", inspection.get("overall_score", 0)),
        "is_manually_verified": bool(report.get("is_manually_verified")),
        "manual_fields_applied": report.get("manual_fields_applied") or [],
        "declarations": [(label, _clean(value), rule) for label, value, rule in declarations],
        "violations": violations,
        "passed_checks": report.get("passed_checks") or [],
        "warnings": report.get("warnings") or [],
        "evidence": inspection.get("evidence") or [],
        "raw_text": report.get("raw_text_dump") or [],
        "language_profile": (report.get("multilingual_profile") or {}).get("dominant_language", "-"),
        "disclaimer": DISCLAIMER,
    }


def _clean(value: Any) -> str:
    if value in (None, "", [], {}):
        return "Not detected"
    return str(value)


def _join(*parts: Any, sep: str = " ") -> Optional[str]:
    kept = [str(p).strip() for p in parts if p not in (None, "", "N/A")]
    return sep.join(kept) if kept else None


def _mrp(meta: Dict[str, Any]) -> Optional[str]:
    mrp = meta.get("mrp")
    if not mrp:
        return None
    suffix = "inclusive of all taxes" if meta.get("taxes_included") else "TAX SUFFIX MISSING"
    return "Rs. %s (%s)" % (mrp, suffix)
